name: Build and publish geth latest

on:
  push:
    branches:
    - master
    tags:        
    - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    container:
      image: golang:latest

    steps:
      - uses: actions/checkout@v3
      - name: Build geth
        run: |
          apt-get update && \
          apt-get install -y build-essential && \
          echo "Compiling all dependencies, running tests and coverage ..." && \
          make geth
      - name: Run unit tests
        # We should not block the release based on unit tests stalling (since those are yet unstable)
        continue-on-error: true
        run: |
          go test ./consensus/cliquepocr/... -coverprofile cover.out
      - name: publish geth latest version
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: build/bin/geth
          asset_name: geth
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release geth with pocr"

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/ethereum-pocr/go-ethereum/base:latest
          context: .
